name: TEST-CI-RERUN

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  test-and-build:
    needs: setup
    strategy:
      matrix:
        envinfo:
          - { name: 'windows-3.6-x64', os: windows-latest, python-version: 3.6.x, python-arch: x64, TZ: 'CST-8', bdist-platform: 'win_amd64'}

    env:
        PYTHONUNBUFFERED: 1
        PYTHONIOENCODING: "utf-8"
        PYTHONHASHSEED: 32
        TZ: ${{ matrix.envinfo.TZ }}
        TESTLOGPATH: "./log_archive/"
        TESTLOGNAME: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.envinfo.python-version}}
        architecture: ${{matrix.envinfo.python-arch}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools pytest pytest-xdist

    - name: Run test case parallel
      timeout-minutes: 5
      shell: bash
      run: |
        pytest test_1.py


